function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 02-Jul-2013 14:48:07

% Create figure
figure1 = figure('PaperSize',[20.98 29.68]);

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineWidth',2);
set(plot1(1),'Marker','o','Color',[1 0 0],'DisplayName','Random');
set(plot1(2),'Marker','square','Color',[0 0 1],'DisplayName','DepthFirst');
set(plot1(3),'Marker','*','Color',[1 1 0],'DisplayName','WidthFirst');
set(plot1(4),'Marker','x','Color',[0 1 0],'DisplayName','Greedy');
set(plot1(5),'DisplayName','Path','Color',[0 0 0]);

% Create legend
legend(axes1,'show');

